services:
  tatotalkserv1:
    image: lyam02/tatotalk:prod
    restart: always
    container_name: PROD_TatoTalk_server_1
    volumes:
      - ./redisson.yaml:/usr/local/tomcat/conf/redisson.yaml
    ports:
      - 8090:8080
    networks:
      - tatotalknetwork

  tatotalkserv2:
    image: lyam02/tatotalk:prod
    restart: always
    container_name: PROD_TatoTalk_server_2
    volumes:
      - ./redisson.yaml:/usr/local/tomcat/conf/redisson.yaml
    ports:
      - 8092:8080
    networks:
      - tatotalknetwork

  nginxloadbalancer:
    build: ./nginx
    restart: always
    container_name: PROD_Nginx_LoadBalancer
    ports:
      - 8091:80
    networks:
      - tatotalknetwork
    depends_on:
      - tatotalkserv1
      - tatotalkserv2

networks:
  tatotalknetwork:
    external: true
    name: PROD-tatotalk-network