services:
  ACC-TatoTalk_server_1:
    image: lyam02/tatotalk:acc
    restart: always
    container_name: TatoTalk_server_1
    volumes:
      - ./redisson.yaml:/usr/local/tomcat/conf/redisson.yaml
    ports:
      - 8080:8080
    networks:
      - tatotalknetwork

  ACC-TatoTalk_server_2:
    image: lyam02/tatotalk:acc
    restart: always
    container_name: TatoTalk_server_2
    volumes:
      - ./redisson.yaml:/usr/local/tomcat/conf/redisson.yaml
    ports:
      - 8082:8080
    networks:
      - tatotalknetwork

  ACC-Nginx_LoadBalancer:
    build: ./nginx
    restart: always
    ports:
      - 8081:80
    networks:
      - tatotalknetwork
    depends_on:
      - tatotalkserv1
      - tatotalkserv2

networks:
  tatotalknetwork:
    external: true
    name: ACC-tatotalk-network