services:
  tatotalkserv1:
    image: lyam02/tatotalk:prod
    restart: always
    container_name: PROD-TatoTalk_server_1
    volumes:
      - fichiertatotalk:/fichierTatoTalk
    ports:
      - 8090:8080
    networks:
      - tatotalknetwork

  tatotalkserv2:
    image: lyam02/tatotalk:prod
    restart: always
    container_name: PROD-TatoTalk_server_2
    volumes:
      - fichiertatotalk:/fichierTatoTalk
    ports:
      - 8092:8080
    networks:
      - tatotalknetwork

  nginxloadbalancer:
    build: ./nginx
    restart: always
    container_name: PROD-Nginx_LoadBalancer
    ports:
      - 8091:80
    networks:
      - tatotalknetwork
    depends_on:
      - tatotalkserv1
      - tatotalkserv2

volumes:
  fichiertatotalk:
    external: true
    name: PROD-fichiertatotalk

networks:
  tatotalknetwork:
    external: true
    name: PROD-tatotalk-network